- name: Create a login user
  user:
    name: "{{ user }}" 
    groups:
      - docker
    state: present
    shell: /bin/bash
    system: yes
    createhome: yes
    home: "/home/{{ user }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: fetch first pub key 
  ansible.builtin.fetch:
    src: /home/{{ user }}/.ssh/id_rsa.pub
    dest: /tmp/id_rsa.pub
    flat: yes

- name: Set authorized key taken from file
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ lookup('file', '/tmp/id_rsa.pub') }}"  

- name: Download RKE binary
  get_url:
    url: "https://github.com/rancher/rke/releases/download/v1.2.8/rke_linux-amd64"
    dest: /usr/local/bin/rke
    mode: "+rx"
    validate_certs: false

- name: "copy cluster.yml"
  template:
    src: "cluster.yml"
    dest: "/home/{{ user }}/cluster.yml"

- name: Run RKE installer
  shell: |
    set -eo pipefail
    /usr/local/bin/rke up --config /home/{{ user }}/cluster.yml| tee /home/{{ user }}/rke-up.log
  become_user: "{{ user }}"
